### PR TITLE
Few fixes + generation frontend files

### PR DESCRIPTION
**Pull request by rabol**
Hi

Fixes a 'bug' in the generation of Event, where a extra " (quote) was added
Fixes a bug where $document is used in the Event class, but in the listener another property is used

New: Create separate label files for the backend
New: with option --frontend: Create frontend files: Controller, Labels, Event, Request, Listener, view, route, Repository
New: with option --force on can overwrite existing files

### CODE REVIEW

**Comment by pqrs** [comment]
Hi @rabol and thank you so much for this pull request! You have done an impressive work here. I have merged it although I had not the time to test it. I hope to have done it right because I ran into some issues while doing it.

Version 1.4 with all your updates is available now in packagist.

**Comment by rabol** [comment]
Hi

Thanks, let me know if you find any problems

**Comment by pqrs** [comment]
Hi @rabol! Sorry I couldn't take a peek to this before, it's been a hard week here. I have just updated the README.md file to include latest changes. Please let me know if I forgot something.

I see you have replicated the backend behavior to the frontend. I just don't see if this is the best way of doing it, I mean, maybe it's better just leaving a very basic controller with no routes or views. Anyway, I'll leave it as you did, as it is an optional feature and maybe some other users come with another ideas.

Finally, I don't know if I did something wrong when merging your PR as you don't appear in the [contributors list](https://github.com/pqrs/l5b-crud/graphs/contributors). Sorry about that, my knowledge of git/github is very basic.

**Comment by rabol** [comment]
No problem
Yes the frontend is a copy of the backend. I was thinking to make a command for each type of generator but did not have the time. 

I have just discovered a small issue in the backend bredcrumb stub 

And for 5.8 the id ( increment) should be a bigIncrement

**Pull request merged**
